services:
  mysql-marketplace:
    image: mysql:8.0
    container_name: mysql-marketplace-container
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-marketplace-volume:/var/lib/mysql
      - mysql-marketplace-volume-config:/etc/mysql
    networks:
      - marketplace_network

  admin-backend:
    container_name: admin-backend-nginx-container
    env_file:
      - .env.docker
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql-marketplace
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    depends_on:
      - mysql-marketplace
    networks:
      - marketplace_network
  
  nginx-admin-backend:
    container_name: nginx-admin-backend-container
    build:
      context: ./admin-backend
      dockerfile: nginx.Dockerfile
    depends_on:
      - admin-backend
    ports:
      - 1040:80
    networks:
      - marketplace_network


  client-backend:
    container_name: client-backend-nginx-container
    env_file:
      - .env.docker
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql-marketplace
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - CRYPTO_HMAC_KEY=${CRYPTO_HMAC_KEY}
    build:
      context: ./client-backend
      dockerfile: Dockerfile
    depends_on:
      - mysql-marketplace
    networks:
      - marketplace_network
  
  nginx-client-backend:
    container_name: nginx-client-backend-container
    build:
      context: ./client-backend
      dockerfile: nginx.Dockerfile
    depends_on:
      - client-backend
    ports:
      - 1050:80
    networks:
      - marketplace_network

  admin-frontend-with-nginx:
    container_name: admin-frontend-container
    environment:
      - VITE_APP_API=${VITE_APP_API_ADMIN}
      - VITE_APP_LOGO_URL=${VITE_APP_LOGO_URL_ADMIN}
    build:
      context: ./admin-frontend
      dockerfile: prod.Dockerfile
      args:
        - VITE_APP_API=${VITE_APP_API_ADMIN}
        - VITE_APP_LOGO_URL=${VITE_APP_LOGO_URL_ADMIN}
    ports:
      - 1020:80

  client-frontend-with-nginx:
    container_name: client-frontend-container
    environment:
      - VITE_APP_API=${VITE_APP_API_CLIENT}
      - VITE_APP_ENCRYPT_KEY=${CRYPTO_KEY}
      - VITE_APP_HMAC_KEY=${CRYPTO_HMAC_KEY}
    build:
      context: ./client-frontend
      dockerfile: prod.Dockerfile
      args:
        - VITE_APP_API=${VITE_APP_API_CLIENT}
        - VITE_APP_ENCRYPT_KEY=${CRYPTO_KEY}
        - VITE_APP_HMAC_KEY=${CRYPTO_HMAC_KEY}
    ports:
      - 1030:80

networks:
  marketplace_network:
    name: marketplace_network
    driver: bridge
volumes:
  mysql-marketplace-volume:
  mysql-marketplace-volume-config:
