services:
  mysql-marketplace:
    image: mysql:8.0
    container_name: marketplace-mysql-container
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-marketplace-volume:/var/lib/mysql
      - mysql-marketplace-volume-config:/etc/mysql
    networks:
      - marketplace_network

  admin-backend:
    image: chinhps/admin-backend-marketplace:latest
    container_name: marketplace-admin-backend-container
    env_file:
      - .env.docker
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql-marketplace
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-marketplace
    networks:
      - marketplace_network
  
  nginx-admin-backend:
    image: chinhps/nginx-admin-backend-marketplace:latest
    container_name: marketplace-nginx-admin-backend-container
    depends_on:
      - admin-backend
    ports:
      - 1040:80
    networks:
      - marketplace_network


  client-backend:
    image: chinhps/client-backend-marketplace:latest
    container_name: marketplace-client-backend-container
    env_file:
      - .env.docker
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql-marketplace
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - CRYPTO_HMAC_KEY=${CRYPTO_HMAC_KEY}
    depends_on:
      - mysql-marketplace
    networks:
      - marketplace_network
  
  nginx-client-backend:
    image: chinhps/nginx-client-backend-marketplace:latest
    container_name: marketplace-nginx-client-backend-container
    depends_on:
      - client-backend
    ports:
      - 1050:80
    networks:
      - marketplace_network

  admin-frontend-with-nginx:
    image: chinhps/admin-frontend-marketplace:latest
    container_name: marketplace-admin-frontend-container
    environment:
      - VITE_APP_API=${VITE_APP_API_ADMIN}
      - VITE_APP_LOGO_URL=${VITE_APP_LOGO_URL_ADMIN}
    ports:
      - 1020:80

  client-frontend-with-nginx:
    image: chinhps/client-frontend-marketplace:latest
    container_name: marketplace-client-frontend-container
    environment:
      - VITE_APP_API=${VITE_APP_API_CLIENT}
      - VITE_APP_ENCRYPT_KEY=${CRYPTO_KEY}
      - VITE_APP_HMAC_KEY=${CRYPTO_HMAC_KEY}
    ports:
      - 1030:80

networks:
  marketplace_network:
    name: marketplace_network
    driver: bridge
volumes:
  mysql-marketplace-volume:
  mysql-marketplace-volume-config:
