FROM node:22-alpine as base

WORKDIR /app
COPY package*.json ./
RUN npm ci

# COPY FILE
COPY . .

# SETUP ENV
ENV NODE_ENV=development

ARG VITE_APP_API
ENV VITE_APP_API=${VITE_APP_API}

ARG VITE_APP_ENCRYPT_KEY
ENV VITE_APP_ENCRYPT_KEY=${VITE_APP_ENCRYPT_KEY}

ARG VITE_APP_HMAC_KEY
ENV VITE_APP_HMAC_KEY=${VITE_APP_HMAC_KEY}

EXPOSE 1030

CMD ["npm", "run", "dev"]